version: "3"
name: "node-building-blocks"
  
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "nodejs-building-blocks-rabbitmq-dev"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"

  redis:
    image: "redis/redis-stack:latest"
    container_name: "nodejs-building-blocks-redis-dev"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - "redis-data:/data"


volumes:
  redis-data: 
    driver: local

  rabbitmq-data:
    driver: local